### ISSUE TITLE
Is Discord Token No Longer Available?

### ISSUE THREAD

**Issue by lukemul69** [paradoxally/HQTrivia#18]
Hey, thanks for providing us with Trivia Swift, I have actually modified it A LOT, I have a total of 10 trivia games on there now and I even made it into an iPhone app. I am trying to set it up with my friends discord token but I have noticed I cant seem to find it anywhere? Or its not in the same place as last time (Local Storage). Any help?

Luke

**Comment by paradoxally** [comment]
Yep, I just updated the README to include the [new method](https://discordhelp.net/discord-token).

**Comment by lukemul69** [comment]
Perfect Thank you!
