### ISSUE TITLE
missing config.plist file

### ISSUE THREAD

**Issue by DaCoderrr** [paradoxally/HQTrivia#19]
![screen shot 2018-09-16 at 11 04 35 pm](https://user-images.githubusercontent.com/43331751/45608013-0ec20800-ba05-11e8-860c-e482672b7e31.png)

Red error on the bottom left-hand corner...
Where is the file supposed to be?

**Comment by paradoxally** [comment]
Where it says `Full Path` on the right, create a .plist there by copying and pasting what is in `Config-default.plist` and then edit the values to your liking. The default .plist can be used, but it's recommended that you have your own values (such as API token and game channels you want to monitor) in `Config.plist`.
